{% set version = "2.3.1" %}

package:
  name: pycodestyle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycodestyle/pycodestyle-{{ version }}.tar.gz
  sha256: 682256a5b318149ca0d2a9185d365d8864a768a28db66a84a2ea946bcc426766

build:
  noarch: python
  entry_points:
    - pycodestyle = pycodestyle:_main

  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  commands:
    - pycodestyle --help
    - pycodestyle --version

about:
  home: https://pycodestyle.readthedocs.io/
  license: MIT
  license_family: MIT
  summary: 'Python style guide checker'
  doc_url: https://pycodestyle.readthedocs.io/
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - jjhelmus
    - sigmavirus24
    - dopplershift
    - ocefpaf
