{% set version = "2.7.0" %}

package:
  name: pycodestyle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycodestyle/pycodestyle-{{ version }}.tar.gz
  sha256: c389c1d06bf7904078ca03399a4816f974a1d590090fecea0c63ec26ebaf1cef

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pycodestyle = pycodestyle:_main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - pycodestyle
  commands:
    - pip check
    - pycodestyle --help
    - pycodestyle --version

about:
  home: https://pycodestyle.readthedocs.io/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python style guide checker
  doc_url: https://pycodestyle.readthedocs.io/
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - sigmavirus24
    - dopplershift
    - ocefpaf
    - bollwyvl
